CREATE OR REPLACE FUNCTION unicen.getMateriasHomologadasEstudiante(p_unicodigo integer, p_id_sede INTEGER, p_id_plan_estudio_nueva integer, p_id_plan_estudio_antigua integer)
 RETURNS TABLE(
    id_materia_antigua INTEGER, 
    id_gestion_antigua INTEGER,
    gestion_antigua CHARACTER VARYING,
    semestre_antigua INTEGER,
    cod_materia_antigua CHARACTER VARYING,
    nombre_materia_antigua CHARACTER VARYING, 
    nota_materia_antigua DOUBLE PRECISION , 
    id_materia_nueva INTEGER,
    semestre_nueva INTEGER, 
    cod_materia_nueva CHARACTER VARYING,
    nombre_materia_nueva CHARACTER VARYING, 
    nota_materia_nueva DOUBLE PRECISION,
    id_gestion_nueva INTEGER,
    estado CHARACTER VARYING)
 AS $$
 BEGIN
 RETURN QUERY

    select 
    hom.id_materia_antigua,
    nt.id_gestion, 
    ges.nombre as gestion_antigua,
    nv1.nivel,
    mat1.cod_materia,
    mat1.nombre, 
    nt.nf as nota_antigua, 
    hom.id_materia_nueva, 
    nv2.nivel,
    mat2.cod_materia,
    mat2.nombre, 
    CASE WHEN nt2.nf IS NOT NULL THEN nt2.nf ELSE nt.nf END as nota_nueva,
    CASE WHEN nt2.id_gestion IS NOT NULL THEN nt2.id_gestion ELSE NULL END as gestion_nueva,  
    CASE WHEN nt2.paralelo IS NULL THEN 'NO HOMOLOGADO' ELSE nt2.paralelo END as estado
    from unicen.equivalencia_homologacion hom 
    JOIN (select * from unicen.notahom nAux where nAux.unicodigo = p_unicodigo) nt ON nt.id_materia = hom.id_materia_antigua AND nt.id_sede = hom.id_sede AND nt.id_plan_estudio = hom.id_plan_estudio_antigua
    JOIN unicen.materia mat1 ON mat1.id_materia = hom.id_materia_antigua AND mat1.id_sede = hom.id_sede
    JOIN unicen.materia mat2 ON mat2.id_materia = hom.id_materia_nueva AND mat2.id_sede = hom.id_sede
    JOIN unicen.plan_materia pm1 ON pm1.id_materia = mat1.id_materia AND pm1.id_sede = mat1.id_sede AND pm1.id_plan_estudio = hom.id_plan_estudio_antigua
    JOIN unicen.plan_materia pm2 ON pm2.id_materia = mat2.id_materia AND pm2.id_sede = mat2.id_sede AND pm2.id_plan_estudio = hom.id_plan_estudio_nueva
    JOIN unicen.nivel nv1 ON nv1.id_nivel = pm1.id_nivel
    JOIN unicen.nivel nv2 ON nv2.id_nivel = pm2.id_nivel
    JOIN unicen.gestion ges ON ges.id_gestion = nt.id_gestion
    LEFT JOIN
    unicen.nota nt2 ON nt2.id_materia = hom.id_materia_nueva AND nt2.id_sede = hom.id_sede AND nt2.id_plan_estudio = hom.id_plan_estudio_nueva AND nt2.unicodigo = nt.unicodigo
    where hom.estado = 'TERMINADO' and (nt2.paralelo IN ('HOMOLOGADO', 'PREHOMOLOGADO') OR nt2.paralelo IS NULL) AND id_plan_estudio_antigua = p_id_plan_estudio_antigua and id_plan_estudio_nueva = p_id_plan_estudio_nueva AND nt.unicodigo = p_unicodigo AND hom.id_sede = p_id_sede AND nt.nf > 50 ORDER BY nv2.nivel;
END;
$$ LANGUAGE plpgsql;


SELECT * FROM unicen.nota where unicodigo = 34504 and id_sede = 1;

select * from unicen.notahom where unicodigo = 34504;

-- Generated by the database client.
CREATE TABLE unicen.estudiantecarecohom(
    id_estudiantecarecohom SERIAL NOT NULL,
    unicodigo integer,
    id_estudiante integer,
    id_plan_estudio integer,
    i_plan_economico integer,
    f_registro timestamp without time zone,
    id_usuario integer,
    estado varchar(50),
    id_carrera integer,
    id_sede integer,
    PRIMARY KEY(id_estudiantecarecohom)
);
DROP FUNCTION IF EXISTS unicen.getMateriasHomologadasEstudiante(integer, INTEGER, integer,integer);

CREATE OR REPLACE FUNCTION unicen.setnotahomologada(p_unicodigo INTEGER, p_id_materia INTEGER, p_plan_estudio INTEGER, p_nota DOUBLE PRECISION, p_id_sede INTEGER)
 RETURNS VOID
 AS $$
 DECLARE
 v_gestion_antigua INTEGER;
 BEGIN
    IF EXISTS (SELECT 1 FROM unicen.nota WHERE id_materia = p_id_materia AND id_plan_estudio = p_plan_estudio AND unicodigo = p_unicodigo AND id_sede = p_id_sede) THEN
        UPDATE unicen.nota SET nf = p_nota WHERE id_materia = p_id_materia AND id_plan_estudio = p_plan_estudio AND unicodigo = p_unicodigo AND id_sede = p_id_sede;
    ELSE
        SELECT id_gestion INTO v_gestion_antigua FROM unicen.hom_estudiante WHERE unicodigo = p_unicodigo AND id_sede = p_id_sede;

        INSERT INTO unicen.nota (unicodigo, id_materia, id_plan_estudio, nf,nfr, id_sede, paralelo, obs, estnota, est, id_gestion, pp, sp, tp, ef, ast, si, ma, gr, id_turno) VALUES (p_unicodigo, p_id_materia, p_plan_estudio, p_nota,p_nota, p_id_sede,  'PREHOMOLOGADO','PREHOMOLOGADO', 'APROBADO', 'ACTIVO', v_gestion_antigua, 0, 0, 0, 0, 0, 0, 0,0,0);

        UPDATE unicen.hom_estudiante SET estado = 'PREHOMOLOGADO', fecha_prehomologacion = CURRENT_DATE WHERE unicodigo = p_unicodigo AND id_sede = p_id_sede;
    END IF;
 END;
$$ LANGUAGE plpgsql;


CREATE OR REPLACE FUNCTION unicen.est_listarplanesestudioantiguo(p_unicodigo INTEGER, p_id_sede INTEGER)
 RETURNS TABLE(id_plan_estudio INTEGER, tipo_plan_estudio CHARACTER VARYING)
 AS $$
 BEGIN
 RETURN QUERY
    SELECT pe.id_plan_estudio, tp.descripcion FROM unicen.plan_estudio pe
    JOIN unicen.estudiantecarecohom ech ON pe.id_plan_estudio = ech.id_plan_estudio AND pe.id_sede = ech.id_sede JOIN unicen.tipo_plan_estudio tp ON tp.id_sede = pe.id_sede AND tp.id_tipo_plan_estudio = pe.id_tipo_plan_estudio
    WHERE ech.unicodigo = p_unicodigo AND ech.id_sede = p_id_sede;
END;
$$ LANGUAGE plpgsql;

SELECT * FROM unicen.est_listarplanesestudioantiguo(34504,1);

DROP Table IF EXISTS unicen.hom_estudiante;

CREATE TABLE unicen.hom_estudiante (
    id_hom_estudiante SERIAL NOT NULL,
    unicodigo INTEGER,
    id_carrera INTEGER,
    id_plan_estudio_antigua INTEGER,
    id_plan_estudio_nueva INTEGER,
    estado CHARACTER VARYING,
    id_gestion INTEGER,
    id_sede INTEGER,
    fecha_prehomologacion TIMESTAMP WITHOUT TIME ZONE,
    fecha_homologacion date,
    resolucion CHARACTER VARYING,
    observacion CHARACTER VARYING,
    fecha_reptec DATE,
    tipo_resolucion CHARACTER VARYING,
    rr_vv CHARACTER VARYING,
    PRIMARY KEY(id_hom_estudiante)
);

ALTER TABLE unicen.hom_estudiante ADD COLUMN nro_documento INTEGER NOT NULL DEFAULT nextval('documentos_nro_seq');

ALTER TABLE unicen.hom_estudiante ADD COLUMN ith VARCHAR(10);

CREATE SEQUENCE documentos_nro_seq
START 1
INCREMENT 1
MINVALUE 1
MAXVALUE 999
CYCLE;

ALTER TABLE unicen.hom_estudiante DROP COLUMN nro_documento ;

CREATE OR REPLACE FUNCTION unicen.iniciarProcesoHomologacionEstudiante(
    p_unicodigo INTEGER,
    p_id_carrera INTEGER, 
    p_id_plan_estudio_nueva INTEGER, 
    p_id_plan_estudio_antigua INTEGER, 
    p_id_sede INTEGER,
    p_id_gestion INTEGER
    )
 RETURNS VOID
 AS $$
 BEGIN
    IF p_id_plan_estudio_antigua = p_id_plan_estudio_nueva THEN
        RAISE EXCEPTION 'El plan de estudio antiguo debe ser diferente del plan de estudio nuevo';
    END IF;

    -- CAMBIAR TIPO DE ESTUDIANTE A HOMOLOGADO (2)
    
    UPDATE unicen.estudiante SET tipo_estudiante = 2 WHERE unicodigo = p_unicodigo AND id_sede = p_id_sede;

    -- INSERTAR DATOS A HOM_ESTUDIANTE

    INSERT INTO unicen.hom_estudiante (unicodigo, id_carrera, id_plan_estudio_antigua, id_plan_estudio_nueva, estado, id_gestion, id_sede) VALUES (p_unicodigo, p_id_carrera, p_id_plan_estudio_antigua, p_id_plan_estudio_nueva, 'INICIADO', p_id_gestion, p_id_sede);
    -- INSERTAR DATOS A CARECOHOM

    INSERT INTO unicen.estudiantecarecohom 
    SELECT *
    FROM unicen.estudiantecareco
    WHERE unicodigo = p_unicodigo AND id_carrera = p_id_carrera AND id_plan_estudio = p_id_plan_estudio_antigua AND id_sede = p_id_sede;

    -- CAMBIAR PLAN DE ESTUDIO DE ESTUDIANTECARECO
    UPDATE unicen.estudiantecareco
    SET id_plan_estudio = p_id_plan_estudio_nueva
    WHERE unicodigo = p_unicodigo AND id_carrera = p_id_carrera AND id_plan_estudio = p_id_plan_estudio_antigua AND id_sede = p_id_sede;

    -- MOVER DATOS DE NOTA A NOTAHOM
    INSERT INTO unicen.notahom 
    SELECT *
    FROM unicen.nota
    WHERE unicodigo = p_unicodigo AND id_plan_estudio = p_id_plan_estudio_antigua AND id_sede = p_id_sede;

    -- ELIMINAR DATOS DE NOTA
    DELETE FROM unicen.nota
    WHERE unicodigo = p_unicodigo AND id_plan_estudio = p_id_plan_estudio_antigua AND id_sede = p_id_sede;

 END;

$$ LANGUAGE plpgsql;

drop Procedure if EXISTS pr_iniciar_proceso_de_homologacion(integer, integer, integer, integer, integer, integer);

CREATE OR REPLACE PROCEDURE unicen.pr_iniciar_proceso_de_homologacion(
    p_unicodigo INTEGER,
    p_id_carrera INTEGER, 
    p_id_plan_estudio_nueva INTEGER, 
    p_id_plan_estudio_antigua INTEGER, 
    p_id_sede INTEGER,
    p_id_gestion INTEGER
)
AS $$
    BEGIN
        IF p_id_plan_estudio_antigua = p_id_plan_estudio_nueva THEN
        RAISE EXCEPTION 'El plan de estudio antiguo debe ser diferente del plan de estudio nuevo';
    END IF;

    -- CAMBIAR TIPO DE ESTUDIANTE A HOMOLOGADO (2)
    
    UPDATE unicen.estudiante SET tipo_estudiante = 2 WHERE unicodigo = p_unicodigo AND id_sede = p_id_sede;

    -- INSERTAR DATOS A HOM_ESTUDIANTE

    INSERT INTO unicen.hom_estudiante (unicodigo, id_carrera, id_plan_estudio_antigua, id_plan_estudio_nueva, estado, id_gestion, id_sede) VALUES (p_unicodigo, p_id_carrera, p_id_plan_estudio_antigua, p_id_plan_estudio_nueva, 'INICIADO', p_id_gestion, p_id_sede);
    -- INSERTAR DATOS A CARECOHOM

    INSERT INTO unicen.estudiantecarecohom 
    SELECT *
    FROM unicen.estudiantecareco
    WHERE unicodigo = p_unicodigo AND id_carrera = p_id_carrera AND id_plan_estudio = p_id_plan_estudio_antigua AND id_sede = p_id_sede;

    -- CAMBIAR PLAN DE ESTUDIO DE ESTUDIANTECARECO
    UPDATE unicen.estudiantecareco
    SET id_plan_estudio = p_id_plan_estudio_nueva
    WHERE unicodigo = p_unicodigo AND id_carrera = p_id_carrera AND id_plan_estudio = p_id_plan_estudio_antigua AND id_sede = p_id_sede;

    -- MOVER DATOS DE NOTA A NOTAHOM
    INSERT INTO unicen.notahom 
    SELECT *
    FROM unicen.nota
    WHERE unicodigo = p_unicodigo AND id_plan_estudio = p_id_plan_estudio_antigua AND id_sede = p_id_sede;

    -- ELIMINAR DATOS DE NOTA
    DELETE FROM unicen.nota
    WHERE unicodigo = p_unicodigo AND id_plan_estudio = p_id_plan_estudio_antigua AND id_sede = p_id_sede;

    COMMIT;
    END;
$$ LANGUAGE plpgsql;

CALL unicen.pr_iniciar_proceso_de_homologacion(34504, 79, 14, 112, 1, 105);

select unicen.cancelarProcesoDeHomologacionEstudiante(34504,79,14,112,1);
begin;

ROLLBACK;
DELETE FROM unicen.nota where unicodigo = 9269 and id_plan_estudio = 41;

SELECT * FROM unicen.nota where unicodigo = 9269 and id_plan_estudio = 41;


select unicen.cancelarProcesoDeHomologacionEstudiante(10151,79,14,112,1);

SELECT * from unicen.notahom where unicodigo = 9269 and id_sede = 1;

COMMIT;





SELECT * from unicen.nota where id_plan_estudio = 14 and unicodigo = 10151;


select * from unicen.hom_estudiante where unicodigo = 9269 and id_sede = 1;
select unicen.cancelarProcesoDeHomologacionEstudiante(9269,77,41,106,1);


select * from unicen.hom_estudiante where unicodigo = 34504 and id_sede = 1;

select * from unicen.factura where numero_factura = '14858';

select * from unicen.notahom where unicodigo = 34504;

DROP FUNCTION IF EXISTS unicen.obtenerDatosEstudianteHomologado(p_unicodigo INTEGER, p_id_sede INTEGER);

CREATE OR REPLACE FUNCTION unicen.obtenerDatosEstudianteHomologado(p_unicodigo INTEGER, p_id_sede INTEGER)
    RETURNS TABLE (
        id_hom_estudiante INTEGER,
        id_plan_estudio_antiguo INTEGER,
        id_plan_estudio_nuevo INTEGER,
        nombre_plan_estudio_nuevo CHARACTER VARYING,
        nombre_plan_estudio_antiguo CHARACTER VARYING,
        id_gestion INTEGER,
        gestion CHARACTER VARYING,
        estado CHARACTER VARYING,
        fecha_homologacion DATE,
        fecha_prehomologacion TIMESTAMP WITHOUT TIME ZONE,
        resolucion CHARACTER VARYING,
        observacion CHARACTER VARYING,
        tipo_resolucion CHARACTER VARYING,
        ith VARCHAR(10)
    )
AS $$
BEGIN
    RETURN QUERY
    SELECT he.id_hom_estudiante,he.id_plan_estudio_antigua, he.id_plan_estudio_nueva, tpe_nuevo.descripcion, tpe_antiguo.descripcion, he.id_gestion, ges.nombre, he.estado, he.fecha_homologacion, he.fecha_prehomologacion, he.resolucion, he.observacion, he.tipo_resolucion, he.ith
    FROM unicen.hom_estudiante he
    JOIN unicen.plan_estudio pe_nuevo ON he.id_plan_estudio_nueva = pe_nuevo.id_plan_estudio
    JOIN unicen.tipo_plan_estudio tpe_nuevo ON pe_nuevo.id_tipo_plan_estudio = tpe_nuevo.id_tipo_plan_estudio AND tpe_nuevo.id_sede = pe_nuevo.id_sede
    JOIN unicen.plan_estudio pe_antiguo ON he.id_plan_estudio_antigua = pe_antiguo.id_plan_estudio
    JOIN unicen.tipo_plan_estudio tpe_antiguo ON pe_antiguo.id_tipo_plan_estudio = tpe_antiguo.id_tipo_plan_estudio AND tpe_antiguo.id_sede = pe_antiguo.id_sede
    JOIN unicen.gestion ges ON ges.id_gestion = he.id_gestion
    WHERE he.unicodigo = p_unicodigo AND he.id_sede = p_id_sede;
END;
$$ LANGUAGE plpgsql;




DROP FUNCTION IF EXISTS unicen.listarEstudiantesHomologados(p_id_sede INTEGER);

CREATE OR REPLACE FUNCTION unicen.listarEstudiantesHomologados(p_id_sede INTEGER)
 RETURNS TABLE (
    id_hom_estudiante INTEGER,
    unicodigo INTEGER,
    nombre_estudiante CHARACTER VARYING,
    nombre_carrera CHARACTER VARYING,
    gestion CHARACTER VARYING,
    id_carrera INTEGER,
    id_plan_estudio_antigua INTEGER,
    id_plan_estudio_nueva INTEGER,
    estado CHARACTER VARYING,
    id_gestion INTEGER,
    fecha_prehomologacion TIMESTAMP WITHOUT TIME ZONE,
    fecha_homologacion date,
    resolucion CHARACTER VARYING,
    observacion CHARACTER VARYING,
    tipo_resolucion CHARACTER VARYING,
    ith VARCHAR(10)
 )
 AS $$
 BEGIN
 RETURN QUERY
    SELECT he.id_hom_estudiante, he.unicodigo, (est.nombres || ' ' || est.paterno || ' ' || est.materno):: CHARACTER VARYING, car.nombre, ges.nombre, he.id_carrera, he.id_plan_estudio_antigua, he.id_plan_estudio_nueva, he.estado, he.id_gestion, he.fecha_prehomologacion, he.fecha_homologacion, he.resolucion, he.observacion, he.tipo_resolucion, he.ith
    FROM unicen.hom_estudiante he JOIN unicen.estudiante est ON he.unicodigo = est.unicodigo AND est.id_sede = he.id_sede
    JOIN unicen.carrera car ON he.id_carrera = car.id_carrera AND car.id_sede = he.id_sede JOIN unicen.gestion ges ON ges.id_gestion = he.id_gestion
    WHERE he.id_sede = p_id_sede;
END;
$$ LANGUAGE plpgsql;


DROP FUNCTION IF EXISTS unicen.terminarProcesoDeHomologacion(p_unicodigo INTEGER, p_id_hom_estudiante INTEGER, p_id_sede INTEGER, p_resolucion CHARACTER VARYING, p_observacion CHARACTER VARYING, p_tipo_resolucion CHARACTER VARYING, p_fecha_resolucion DATE);
CREATE OR REPLACE FUNCTION unicen.terminarProcesoDeHomologacion(p_unicodigo INTEGER, p_id_hom_estudiante INTEGER, p_id_sede INTEGER, p_resolucion CHARACTER VARYING, p_observacion CHARACTER VARYING, p_tipo_resolucion CHARACTER VARYING, p_fecha_resolucion DATE)
 RETURNS VOID
 AS $$
 DECLARE
    v_id_plan_estudio INTEGER;
    v_gestion CHARACTER VARYING;
    v_year CHARACTER VARYING;
    v_ith VARCHAR(10);
    v_antiguo_paralelo CHARACTER VARYING;
 BEGIN
    -- ACTUALIZAR ESTADO EN HOM_ESTUDIANTE
    UPDATE unicen.hom_estudiante
    SET estado = 'HOMOLOGADO',
        fecha_homologacion = p_fecha_resolucion,
        resolucion = p_resolucion,
        observacion = p_observacion,
        tipo_resolucion = p_tipo_resolucion
    WHERE id_hom_estudiante = p_id_hom_estudiante;

    SELECT ges.nombre, id_plan_estudio_nueva, he.ith INTO v_gestion, v_id_plan_estudio, v_ith FROM unicen.hom_estudiante he JOIN unicen.gestion ges ON ges.id_gestion = he.id_gestion
    WHERE he.id_hom_estudiante = p_id_hom_estudiante;

    SELECT EXTRACT(YEAR FROM p_fecha_resolucion)::CHARACTER VARYING INTO v_year;
    -- ACTUALIZAR NOTAS PREHOMOLOGADAS A HOMOLOGADAS
    
    UPDATE unicen.nota 
    SET paralelo = 'HOMOLOGADO', obs = ('Homol. RR ' || p_resolucion || '/' || v_year || ' ITH No.' || v_ith || '-' || substring(v_gestion,'.+/') || v_year) :: CHARACTER VARYING
    WHERE unicodigo = p_unicodigo AND id_sede = p_id_sede AND id_plan_estudio = v_id_plan_estudio AND paralelo = 'PREHOMOLOGADO';
    
 END;
$$ LANGUAGE plpgsql;

SELECT DISTINCT paralelo from unicen.nota;


SELECT * FROM unicen.notahom;



DROP FUNCTION IF EXISTS unicen.updateEstudianteHomologado(p_id_hom_estudiante INTEGER, p_id_gestion INTEGER, p_resolucion CHARACTER VARYING, p_observacion CHARACTER VARYING, p_tipo_resolucion CHARACTER VARYING, p_fecha_resolucion DATE);

CREATE OR REPLACE FUNCTION unicen.updateEstudianteHomologado(p_id_hom_estudiante INTEGER, p_id_gestion INTEGER, p_resolucion CHARACTER VARYING, p_observacion CHARACTER VARYING, p_tipo_resolucion CHARACTER VARYING, p_fecha_resolucion DATE, p_ith VARCHAR(10))
 RETURNS VOID
 AS $$
 DECLARE
 v_id_gestion INTEGER;
 v_id_sede INTEGER;
 v_id_plan_estudio_nueva INTEGER;
 v_unicodigo INTEGER;
 v_resolucion CHARACTER VARYING;
 v_nro_documento INTEGER;
 v_fecha_homologacion DATE;
 v_year CHARACTER VARYING;
 v_gestion CHARACTER VARYING;
 v_ith VARCHAR(10);
 BEGIN
    SELECT id_gestion,id_sede,id_plan_estudio_nueva,unicodigo, resolucion, nro_documento, fecha_homologacion, ith INTO v_id_gestion, v_id_sede, v_id_plan_estudio_nueva, v_unicodigo, v_resolucion, v_nro_documento, v_fecha_homologacion, v_ith FROM unicen.hom_estudiante WHERE id_hom_estudiante = p_id_hom_estudiante;

    IF v_id_gestion != p_id_gestion THEN
        UPDATE unicen.nota 
        SET id_gestion = p_id_gestion
        WHERE unicodigo = v_unicodigo AND id_sede = v_id_sede AND id_plan_estudio = v_id_plan_estudio_nueva AND paralelo = 'HOMOLOGADO';
    END IF;

    IF v_resolucion != p_resolucion OR v_fecha_homologacion != p_fecha_resolucion OR v_ith != p_ith THEN

        v_gestion := (SELECT nombre FROM unicen.gestion WHERE id_gestion = p_id_gestion);
        v_year := EXTRACT(YEAR FROM p_fecha_resolucion)::CHARACTER VARYING;

        UPDATE unicen.nota 
        SET obs = ('Homol. RR ' || p_resolucion || ' ITH No. ' ||  p_ith || '-' || substring(v_gestion, '.+/') ||  v_year):: CHARACTER VARYING
        
        WHERE unicodigo = v_unicodigo AND id_sede = v_id_sede AND id_plan_estudio = v_id_plan_estudio_nueva AND paralelo = 'HOMOLOGADO';
    END IF; 

    UPDATE unicen.hom_estudiante he
    SET id_gestion = p_id_gestion,
        resolucion = p_resolucion,
        observacion = p_observacion,
        tipo_resolucion = p_tipo_resolucion,
        fecha_homologacion = p_fecha_resolucion,
        ith = p_ith
    WHERE he.id_hom_estudiante = p_id_hom_estudiante;
 END;
$$ LANGUAGE plpgsql;

CREATE OR REPLACE FUNCTION unicen.cancelarProcesoDeHomologacionEstudiante(
    p_unicodigo INTEGER,
    p_id_carrera INTEGER, 
    p_id_plan_estudio_antiguo INTEGER, 
    p_id_plan_estudio_nuevo INTEGER, 
    p_id_sede INTEGER
    )
 RETURNS VOID
 AS $$
 BEGIN

    -- CAMBIAR TIPO DE ESTUDIANTE A REGULAR (1)
    
    UPDATE unicen.estudiante SET tipo_estudiante = 1 WHERE unicodigo = p_unicodigo AND id_sede = p_id_sede;

    -- ELIMINAR DATOS DE HOM_ESTUDIANTE

    DELETE FROM unicen.hom_estudiante WHERE unicodigo = p_unicodigo AND id_sede = p_id_sede;

    -- RESTAURAR PLAN DE ESTUDIO DE ESTUDIANTECARECO
    UPDATE unicen.estudiantecareco
    SET id_plan_estudio = p_id_plan_estudio_antiguo
    WHERE unicodigo = p_unicodigo AND id_carrera = p_id_carrera AND id_plan_estudio = p_id_plan_estudio_nuevo AND id_sede = p_id_sede;

    -- ELIMINAR DATOS DE NOTA 

    DELETE FROM unicen.nota WHERE unicodigo = p_unicodigo AND id_sede = p_id_sede AND id_plan_estudio = p_id_plan_estudio_nuevo AND (paralelo = 'HOMOLOGADO' OR paralelo = 'PREHOMOLOGADO');

    -- RESTAURAR DATOS DE NOTA DESDE NOTAHOM
    INSERT INTO unicen.nota 
    SELECT *
    FROM unicen.notahom
    WHERE unicodigo = p_unicodigo AND id_plan_estudio = p_id_plan_estudio_antiguo AND id_sede = p_id_sede;

    -- ELIMINAR DATOS DE NOTAHOM
    DELETE FROM unicen.notahom
    WHERE unicodigo = p_unicodigo AND id_plan_estudio = p_id_plan_estudio_antiguo AND id_sede = p_id_sede;

    -- ELIMINAR DATOS DE CARECOHOM
    DELETE FROM unicen.estudiantecarecohom WHERE unicodigo = p_unicodigo AND id_carrera = p_id_carrera AND id_plan_estudio = p_id_plan_estudio_antiguo AND id_sede = p_id_sede;

 END;
$$ LANGUAGE plpgsql;

select * from unicen.hom_estudiante;

select unicen.cancelarProcesoDeHomologacionEstudiante(34504,79,14,112,1);

select * from unicen.hom_estudiante where unicodigo = 34504 and id_sede = 1;

select tipo_estudiante from unicen.estudiante where unicodigo = 34504 and id_sede = 1;

select * from unicen.nota where unicodigo = 10151 and id_sede = 1;

select unicen.cancelarprocesodehomologacionestudiante(23008,6,134,4,3);

select * from unicen.usuario where unicodigo = 4137;

select nf from unicen.nota where unicodigo = 34504 and id_sede = 1 and id_plan_estudio = 112;

DELETE FROM unicen.nota WHERE unicodigo = 34504 and id_sede = 1 and id_plan_estudio = 112;

update unicen.equivalencia_homologacion set estado = 'EMPAREJADA' where estado = 'TERMINADO' and id_plan_estudio_antigua = 14;

update unicen.equivalencia_homologacion set estado = 'TERMINADO' where estado = 'EMPAREJADA' and id_plan_estudio_antigua = 14;

select * from unicen.equivalencia_homologacion;


select * from unicen.estudiantecarecohom where unicodigo = 23008 and id_sede = 3;


select * from unicen.notahom where unicodigo = 23008;

select * from unicen.carrera where nombre like '%KI%';

INSERT INTO unicen.estudiantecarecohom 
    SELECT *
    FROM unicen.estudiantecareco
    WHERE unicodigo = 34504 AND id_carrera = 79 AND id_plan_estudio = 14 AND id_sede = 1;

select unicen.iniciarProcesoHomologacionEstudiante(34504,79 ,112, 14, 1, 105);

DELETE FROM unicen.hom_estudiante WHERE id_hom_estudiante = 7;
SELECT * FROM unicen.hom_estudiante;

select * from unicen.notahom;

select * from unicen.estudiantecarecohom;

select tipo_estudiante from unicen.estudiante WHERE unicodigo = 34504;

select * from unicen.nota where unicodigo = 34504;

UPDATE unicen.estudiante SET tipo_estudiante = 1 WHERE unicodigo = 34504;



INSERT INTO unicen.notahom 
SELECT *
FROM unicen.nota
WHERE unicodigo = 16050 AND id_plan_estudio = 111 AND id_sede = 1;


SELECT * FROM unicen.carrera WHERE id_carrera = 109;


select * from unicen.equivalencia_homologacion WHERE id_plan_estudio_nueva= 109 AND estado = 'TERMINADO';

UPDATE unicen.equivalencia_homologacion SET estado = 'EMPAREJADA' WHERE id_plan_estudio_nueva= 109 AND estado = 'TERMINADO';

select * from unicen.estudiante where unicodigo = 35158;

select * from unicen.obtenerDatosEstudianteHomologado(34504,1);




select * from unicen.listarEstudiantesHomologados(1);


SELECT unicen.terminarProcesoDeHomologacion(34504, 9, 1, '019-A', 'Homologacion exitosa', 'RECTORAL', '2024-06-01');

SELECT * FROM unicen.hom_estudiante WHERE unicodigo = 34504 AND id_sede = 1;

UPDATE unicen.hom_estudiante
    SET estado = 'PREHOMOLOGADO',
        fecha_homologacion = null,
        resolucion = null,
        observacion = null,
        tipo_resolucion = null
WHERE unicodigo = 34504 AND id_sede = 1;


select substring(nombre, '.+/'), nombre from unicen.gestion;

select * from unicen.hom_estudiante WHERE unicodigo = 34504 AND id_sede = 1;

UPDATE unicen.hom_estudiante
    SET estado = 'PREHOMOLOGADO',
        fecha_homologacion = null,
        resolucion = null,
        observacion = null,
        tipo_resolucion = null

WHERE id_hom_estudiante = 9;


SELECT * FROM unicen.hom_estudiante WHERE unicodigo = 34504 AND id_sede = 1;

UPDATE unicen.nota 
    SET paralelo = 'PREHOMOLOGADO', obs = 'PREHOMOLOGADO'
    WHERE unicodigo = 34504 AND id_sede = 1 AND id_plan_estudio = 112 AND paralelo = 'HOMOLOGADO';


WHERE id_hom_estudiante = 9;

SELECT * FROM unicen.notahom WHERE unicodigo = 34504 AND id_sede = 1 AND id_plan_estudio = 14;

SELECT * FROM unicen.nota WHERE unicodigo = 34504 AND id_sede = 1 AND id_plan_estudio = 112;


DELETE FROM unicen.nota WHERE unicodigo = 34504 AND id_sede = 1 AND id_plan_estudio = 112;

SELECT * FROM unicen.estudiantecarecohom WHERE unicodigo = 34504;

UPDATE unicen.estudiantecareco
    SET id_plan_estudio = 14
WHERE unicodigo = 34504 AND id_sede = 1 AND id_plan_estudio = 112;

DELETE FROM unicen.estudiantecarecohom WHERE unicodigo = 34504;

DELETE FROM unicen.hom_estudiante WHERE unicodigo = 34504 AND id_sede = 1;

INSERT INTO unicen.nota 
SELECT * FROM unicen.notahom
WHERE unicodigo = 34504 AND id_sede = 1;


DELETE FROM unicen.notahom
WHERE unicodigo = 34504 AND id_sede = 1;

UPDATE unicen.estudiante 
SET tipo_estudiante = 1
WHERE unicodigo = 34504 AND id_sede = 1;





select unicen.updateEstudianteHomologado(16,106,'016','Actualizacion de homologacion','RECTORAL', '2024-06-15','ITH-001');

select * from unicen.nota where unicodigo = 34504 and id_sede = 1 and id_plan_estudio = 112;


select * from unicen.hom_estudiante WHERE unicodigo = 34504 AND id_sede = 1;

select obs from unicen.nota where unicodigo = 34504 and id_sede = 1 and id_plan_estudio = 112;

SELECT 
    constraint_name, 
    table_name, 
    constraint_type 
FROM 
    information_schema.table_constraints 
WHERE 
    constraint_schema = 'unicen' and constraint_type ='UNIQUE';

ALTER TABLE unicen.hom_estudiante
ADD CONSTRAINT unique_planes_estudio UNIQUE (unicodigo, id_plan_estudio_antigua, id_plan_estudio_nueva, id_sede);


select * from unicen.estudiante where unicodigo = 34504 and id_sede = 1;

SELECT * FROM unicen.hom_estudiante where unicodigo = 23008;

select * from unicen.estudiantecareco where unicodigo = 23008;

select * from unicen.notahom where unicodigo = 23008;


select * from unicen.estudiantecarecohom where unicodigo = 23008 and id_sede = 3;
select * from unicen.estudiantecarecohom where unicodigo = 35543 and id_sede = 3;

select * from unicen.estudiantecareco where unicodigo = 23008 and id_sede = 3;

select * from unicen.hom_estudiante where unicodigo = 35543 and id_sede = 3;
select unicen.cancelarProcesoDeHomologacionEstudiante(23008,6,4,134,3);
select unicen.cancelarProcesoDeHomologacionEstudiante(35543,13,17,130,3);


select * from unicen.estudiante where unicodigo = 23008 and id_sede = 3;

select * from unicen.hom_estudiante where unicodigo = 23008 and id_sede = 3;

select * from unicen.personal where unicodigo = 4137;

select * from unicen.usuario where unicodigo = 4137;

begin;

COMMIT;


select * from unicen.personal where id_sede = 1 and paterno like '%POR%';


SELECT * FROM unicen.nota where unicodigo = 35728;


SELECT * FROM unicen.equivalencia_homologacion where id_plan_estudio_antigua = 14;